
trainer:
  epochs: 100
  batch_size: 64
  seed: 42
  backbone_learning_rate: 1e-6
  encoder_learning_rate: 1e-4
  decoder_learning_rate: 1e-5
  output_head_learning_rate: 1e-5
  optimizer: "AdamW"
  log_interval: 10
  num_log_images: 8
  viz_score_threshold: 0.5
  epoch_to_unfreeze_backbone: 300
  epoch_to_unfreeze_decoder: 30
  epoch_to_unfreeze_output_head: 30
  loss:
    name: "giouloss" # Options: "giouloss", "ciouloss"
    class_cost: 1.0
    bbox_cost: 5.0
    giou_cost: 2.0  
    num_labels: 91
    eos_coefficient: 0.1
    auxiliary_loss: true
    bbox_loss_coefficient: 5.0
    giou_loss_coefficient: 2.0
    decoder_layers: 6
  dataset_name: "mot17" # Options: "coco", "mot17",

model:
  input_size: 224
  num_classes: 92
  detr_name: "facebook/detr-resnet-50" # Options: "facebook/detr-resnet-50" "facebook/detr-resnet-50-dc5"
  num_frames: 4
  spatial_encoder:
    encoder_type: "mamba"
    num_layers: 12
    hidden_state_dim: 64
  temporal_encoder:
    encoder_type: "mamba"
    num_layers: 12
    hidden_state_dim: 64
  backbone:
    freeze_backbone: true
  decoder:
    freeze_decoder: true
    auxiliary_loss: true
  output_head:
    freeze_prediction_head: true
