
trainer:
  epochs: 100
  batch_size: 64
  seed: 42
  encoder_learning_rate: 1e-4
  decoder_learning_rate: 1e-5
  output_head_learning_rate: 1e-5
  optimizer: "AdamW"
  log_interval: 10
  num_log_images: 8
  viz_score_threshold: 0.5
  loss:
    name: "giouloss" # Options: "giouloss", "ciouloss"
    class_cost: 1.0
    bbox_cost: 5.0
    giou_cost: 2.0  
    num_labels: 91
    eos_coefficient: 0.1
    auxiliary_loss: false
    bbox_loss_coefficient: 5.0
    giou_loss_coefficient: 2.0

model:
  input_size: 224
  num_classes: 92
  encoder:
    encoder_type: "detr"
    num_layers: 4
    use_pre_trained: false
  decoder:
    freeze_decoder: false
    epoch_to_unfreeze_decoder: 0
